package WebTable;

import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

public class TypeToSearchWebTable {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ChromeDriver driver = new ChromeDriver();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        try {
            // 2. Navigate to Web Tables Page & Maximize
            driver.manage().window().maximize();
            driver.get("https://demoqa.com/webtables");

            // Define Locators
            By searchBoxLocator = By.id("searchBox");
            // CSS selector that ignores the empty/padded rows generated by the React table grid
             By activeRowsLocator = By.cssSelector(".rt-tbody.rt-tr-group:not(.-padRow)");
 
            // 3. Step 1 & 2: Locate Search Box and input "Legal"
            WebElement searchBox = wait.until(ExpectedConditions.elementToBeClickable(searchBoxLocator));
            String searchKeyword = "Legal";
            searchBox.sendKeys(searchKeyword);

            // Small dynamic wait to allow the table filter processing to complete
            wait.until(ExpectedConditions.textToBePresentInElementLocated(By.className("rt-tbody"), searchKeyword));

            // 4. Expected Verification #1: Assert total row count reduces to only matching entries (1 row)
            List<WebElement> activeRows = driver.findElements(activeRowsLocator);
            int expectedRowCount = 1;
            
            System.out.println("Active rows found after filtering: " + activeRows.size());
            Assert.assertEquals(activeRows.size(), expectedRowCount, "Table did not filter down to the expected row count!");

            // 5. Expected Verification #2: Verify the matching row contains the correct details ("Kierra")
            WebElement matchingRow = activeRows.get(0);
            String rowText = matchingRow.getText();
            
            System.out.println("Row content details:\n" + rowText);
            
            // Assert that the matching row contains the First Name "Kierra"
            Assert.assertTrue(rowText.contains("Kierra"), "The filtered row does not contain the expected name 'Kierra'!");
            System.out.println("Test Status: PASSED - Dynamic filtering verified successfully.");

        } catch (Exception e) {
            System.out.println("Test Status: FAILED due to exception.");
            e.printStackTrace();
        } finally {
            // 6. Close Browser Session
            driver.quit();
        }
		
	}

}
